### ISSUE TITLE
List own entries

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/backend#18]
This endpoint should return a list of device-availability entries that the currently logged-in user has created. I am not sure what the address of the endpoint should be. Maybe `/device-availability?mine=true`?

Request:

```jsx
GET /???
```

Response:

Status code 200:

```jsx
[
  {
    id: int
    deviceId: int,
    comment: string (optional),
    germanPostalCode: string (optional),
    institution: string,
    researchGroup: string (optional)
  }
]
```

**Comment by michael-kamel** [comment]
We could do `/account/me/device_availability_list`. 
Imo, The one you suggested is fine too as long as we stick to a standard for similar endpoints. 
One would be easier to develop and possibly maintain but yields an additional controller, while the other is the opposite.

**Comment by dajenet** [comment]
We could use `/device-availability?account-id={own-id}`.
That would probably be more flexible if we want to display the devices of other users as well in the future.
