### ISSUE TITLE
Edit and delete device availabilities

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/backend#36]
The user who has created a device availability should be able to edit and delete it.

This means creating two endpoints: `PUT /device-availability/{id}` and `DELETE /device-availability/{id}`.

**Comment by michael-kamel** [comment]
The nature of device availabilities is still not very clear. Currently, a user can add multiple availability entries for the same device which seems counter intuitive to me.

**Comment by chaoran-chen** [comment]
Someone could be responsible for device management in two groups or a group could have the same type of device at two different locations.

**Comment by vordemann** [comment]
The PUT request should use the same API structure as POST /device-availability in https://github.com/icebreaker-science/backend/issues/8

**Comment by michael-kamel** [comment]
Which fields should the user be able to update. I can only think of the comment being updatable, changing any other field intuitively changes the identity of the availability entry.
