### ISSUE TITLE
Send welcome and validation email after registration

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/backend#37]
Everyone does it, so shall we... The given email address should be validated during the registration process. I propose the following flow:

1. The user fills out the registration form and submits it. -> `POST /account/register`
2. The system validates the input, create a deactivated account, and sends a welcome and validation email to the given email address containing a link to the following page: `https://{host}/validate-email?key={key}`.
3. When the user navigates to the link, the website will send a request to the following API: `POST /account/validate-email` providing the key in the request body.
4. The system activates the corresponding account.

**Comment by osopromadze** [comment]
Hello @chaoran-chen, I would like to work on this issue.

**Comment by chaoran-chen** [comment]
Hi @osopromadze, that's really nice, thank you! I have assigned the issue to you.
