### ISSUE TITLE
Contact form API needs faster response time

### ISSUE THREAD

**Issue by chaoran-chen** [icebreaker-science/backend#39]
Sending a mail can take a long time. Currently, when the user clicks on "submit", she needs to wait for quite a while. There are two ways to solve it:

- Backend side: the API responds after validating the input but before the email is actually sent.
- Frontend side: the frontend app does not wait for an answer from the backend and directly redirects the user to the next page and shows a notification that the message was sent.

I think that the first option is better (thus this issue here). What do you think?

**Comment by michael-kamel** [comment]
I agree with the first option as well as there is no way to tell if the mail server is actually unresponsive or the backend has any other issue.

**Comment by dajenet** [comment]
I would choose the backend side option too. We can also add a message to the frontend that the user gets a confirmation of the request via mail.
