### ISSUE TITLE
Init database with demo data

### ISSUE THREAD

**Issue by dajenet** [icebreaker-science/backend#45]
It should be possible to initialize the database for development and testing with demo data.

Data that should be added:
- [x] activated accounts
- [x] devices
- [x] device-availabilities 
- [ ] (optional) small network graph

**Comment by chaoran-chen** [comment]
Great idea. This will help new developers a lot to get started.

**Comment by chaoran-chen** [comment]
Shall we close it or would you like to add data for a small network graph as well?

**Comment by michael-kamel** [comment]
> Shall we close it or would you like to add data for a small network graph as well?

If i'm not mistaken, we have functions for adding network data now so that's possible without hard coding things in the scripts, If so, we can do that yes.

**Comment by chaoran-chen** [comment]
Let's close it and discuss the network data part in another issue.
