### ISSUE TITLE
DB Transactions

### ISSUE THREAD

**Issue by michael-kamel** [icebreaker-science/backend#53]
Some of the functionalities require running transactions against the database to avoid inconsistent data.

- [ ] Creation of accounts
- [ ] Update device availability entries (depending on how hibernate handles deletion of entities already in memory)

**Comment by chaoran-chen** [comment]
Could you list the functionalities, please? To ensure that we don't forget them when we tackle this issue and to clearly define the scope of this issue.

**Comment by michael-kamel** [comment]
I added the ones that I think would need some work. if there are others that I've missed, please add them too.
