### ISSUE TITLE
Password strength

### ISSUE THREAD

**Issue by michael-kamel** [icebreaker-science/backend#76]
there are currently no checks for password strength

**Comment by chaoran-chen** [comment]
What would you recommend as a minimal requirement?

**Comment by michael-kamel** [comment]
> What would you recommend as a minimal requirement?

We can use the [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls) guidelines for that however, there doesn't seem to be any goto guidelines for **secure** passwords that are universally agreed upon.
